/**
 * Pool of 100 "based on true events" disclaimer lines (Italian) shown on the
 * black opening screen of each reel. One is picked per video — deterministically
 * from a seed (e.g. the chat id) so the same video always gets the same line but
 * different videos differ. All convey: real facts · real conversations · names
 * changed for privacy.
 */
export const INTRO_DISCLAIMERS: string[] = [
  'Attenzione: i fatti che stai per leggere sono realmente accaduti. Le conversazioni sono vere. I nomi sono stati cambiati per questioni di privacy.',
  'Avvertenza: tutto ciò che leggerai è accaduto davvero. Le chat sono autentiche. I nomi sono stati modificati per tutelare la privacy.',
  'Questa è una storia vera. Le conversazioni non sono inventate. Solo i nomi sono stati cambiati.',
  'I messaggi che seguono sono reali. Nulla è stato romanzato. I nomi sono di fantasia per proteggere le persone coinvolte.',
  'Quello che stai per vedere è successo davvero. Le conversazioni sono riportate fedelmente. I nomi sono stati cambiati.',
  'Basato su fatti realmente accaduti. Le chat sono autentiche, parola per parola. I nomi sono stati alterati per privacy.',
  'Le conversazioni di questo video sono vere. Non abbiamo inventato nulla. Abbiamo solo cambiato i nomi.',
  'Attenzione: questa non è finzione. Tutto è accaduto realmente. I nomi sono stati modificati per riservatezza.',
  'Ogni messaggio che leggerai è reale. I fatti sono autentici. Per privacy, i nomi sono stati cambiati.',
  'Storia vera. Conversazioni vere. Nomi cambiati per proteggere la privacy dei protagonisti.',
  'Avviso: i dialoghi che seguono sono realmente avvenuti. Niente è stato aggiunto o tolto. Solo i nomi sono diversi.',
  'Tutto ciò che vedrai è realmente successo. Le chat sono genuine. I nomi sono stati sostituiti per tutelare le persone.',
  'I fatti narrati in questo video sono autentici. Le conversazioni non sono state modificate. I nomi sì, per privacy.',
  'Questa vicenda è realmente accaduta. I messaggi sono quelli originali. I nomi sono stati cambiati.',
  'Attenzione: ciò che leggerai è tutto vero. Nessuna conversazione è inventata. I nomi sono di fantasia.',
  'Le chat mostrate sono reali al 100%. I fatti sono accaduti davvero. Per riservatezza, i nomi sono stati modificati.',
  'Quanto stai per leggere è successo realmente. Le conversazioni sono autentiche. I nomi sono stati cambiati per privacy.',
  'Nessuna finzione: solo fatti reali. Le conversazioni sono vere. I nomi sono stati alterati per proteggere la privacy.',
  'Questo video racconta fatti realmente accaduti. Le chat sono originali. I nomi sono stati cambiati.',
  'Avvertenza: storia autentica. Messaggi autentici. Nomi modificati per ragioni di privacy.',
  'Tutto vero. Le conversazioni che seguono sono accadute realmente. I nomi sono stati cambiati per discrezione.',
  'I fatti che stai per scoprire sono reali. Le chat non sono state ritoccate. Solo i nomi sono diversi.',
  'Attenzione: ogni parola è autentica. Le conversazioni sono realmente avvenute. I nomi sono stati modificati.',
  "Questa è una vicenda vera, riportata così com'è. Per proteggere i protagonisti, abbiamo cambiato i nomi.",
  'Ciò che vedrai non è una recita. È tutto realmente accaduto. I nomi sono stati cambiati per privacy.',
  'Le conversazioni di questo reel sono autentiche. I fatti sono veri. I nomi sono stati sostituiti per riservatezza.',
  'Avviso: nessun episodio è inventato. Tutto è realmente successo. I nomi sono di fantasia.',
  'I messaggi che leggerai sono reali e non modificati. Per tutela della privacy, i nomi sono stati cambiati.',
  'Questa storia è accaduta davvero. Le chat sono quelle vere. Abbiamo cambiato solo i nomi.',
  'Attenzione: fatti reali, conversazioni reali. I nomi sono stati alterati per proteggere chi vi ha preso parte.',
  'Tutto quello che segue è realmente accaduto. Le conversazioni sono autentiche. I nomi sono stati cambiati per privacy.',
  'Avvertenza: questa non è una storia inventata. È tutto vero. I nomi sono stati modificati per riservatezza.',
  'I dialoghi mostrati sono reali. I fatti sono documentati. Per privacy, i nomi sono diversi da quelli originali.',
  'Quello che stai per leggere è accaduto sul serio. Le chat sono autentiche. I nomi sono stati cambiati.',
  'Storia realmente accaduta. Conversazioni non alterate. Nomi cambiati per proteggere la privacy.',
  'Attenzione: ogni conversazione è vera. Niente è stato sceneggiato. I nomi sono stati modificati.',
  'I fatti raccontati sono autentici e verificati. Le chat sono originali. I nomi sono stati cambiati per riservatezza.',
  'Ciò che leggerai è realmente successo. Non c\'è finzione. I nomi sono di fantasia per tutelare le persone.',
  'Le conversazioni in questo video sono accadute davvero. I nomi, però, sono stati cambiati per privacy.',
  'Avviso: tutto vero, nulla di inventato. I nomi sono stati alterati per proteggere i protagonisti.',
  'Questa vicenda è autentica. I messaggi sono quelli realmente scambiati. Solo i nomi sono stati modificati.',
  'Attenzione: i fatti sono reali e le chat non sono state ritoccate. I nomi sono stati cambiati per riservatezza.',
  'Tutto ciò che vedrai è documentato e vero. Le conversazioni sono autentiche. I nomi sono di fantasia.',
  'I messaggi che seguono sono realmente accaduti. Per rispetto della privacy, i nomi sono stati cambiati.',
  'Questa è una storia realmente accaduta, raccontata senza filtri. I nomi sono stati modificati.',
  'Avvertenza: le conversazioni sono reali, parola per parola. I nomi sono stati cambiati per privacy.',
  'Quello che stai per scoprire è tutto vero. Nessuna chat è inventata. I nomi sono stati alterati.',
  'I fatti di questo video sono accaduti davvero. Le conversazioni sono autentiche. I nomi sono diversi per riservatezza.',
  'Attenzione: nulla è stato romanzato. Tutto è reale. I nomi sono stati cambiati per proteggere la privacy.',
  'Le chat che vedrai sono vere e non modificate. I nomi sono stati sostituiti per tutelare le persone coinvolte.',
  'Storia vera, conversazioni autentiche. I nomi sono stati cambiati per ragioni di privacy.',
  'Attenzione: ciò che leggerai è realmente accaduto. Le chat sono originali. Abbiamo cambiato solo i nomi.',
  'I fatti narrati sono reali. Le conversazioni non sono state inventate. I nomi sono di fantasia.',
  'Tutto quello che segue è autentico. È successo davvero. I nomi sono stati modificati per privacy.',
  'Avviso: questa non è fiction. Le conversazioni sono vere. I nomi sono stati cambiati per riservatezza.',
  'I messaggi che stai per leggere sono reali. Niente è stato alterato, tranne i nomi.',
  'Questa storia è accaduta realmente. Le chat sono autentiche. Per privacy, i nomi sono stati cambiati.',
  'Attenzione: fatti veri, messaggi veri. I nomi sono stati modificati per proteggere chi c\'è dietro.',
  "Quello che vedrai è successo davvero. Le conversazioni sono fedeli all'originale. I nomi sono diversi.",
  'Le vicende mostrate sono reali. Le chat non sono state ritoccate. I nomi sono stati cambiati per privacy.',
  'Tutto vero. Ogni conversazione è realmente avvenuta. I nomi sono stati alterati per riservatezza.',
  'Avvertenza: i fatti che leggerai sono autentici. Le chat sono originali. I nomi sono di fantasia.',
  'Questa è una storia realmente accaduta. Non abbiamo inventato niente. Solo i nomi sono cambiati.',
  'Attenzione: le conversazioni sono vere e documentate. I nomi sono stati modificati per privacy.',
  'I dialoghi che seguono sono reali. Nessuna parola è stata aggiunta. I nomi sono stati cambiati.',
  'Ciò che stai per vedere è tutto autentico. È accaduto davvero. I nomi sono stati sostituiti per riservatezza.',
  'Le chat di questo reel sono reali. I fatti sono veri. Per tutelare la privacy, i nomi sono diversi.',
  'Avviso: storia autentica, conversazioni autentiche. I nomi sono stati cambiati per proteggere le persone.',
  'Tutto ciò che leggerai è realmente successo. Le conversazioni non sono modificate. I nomi sì.',
  'Questa vicenda è vera. I messaggi sono quelli originali. I nomi sono stati cambiati per privacy.',
  'Attenzione: niente finzione, solo realtà. Le chat sono autentiche. I nomi sono stati modificati.',
  'I fatti che stai per leggere sono accaduti davvero. Per riservatezza, i nomi sono stati cambiati.',
  'Quello che segue è tutto vero. Le conversazioni sono reali. I nomi sono di fantasia per privacy.',
  'Storia realmente accaduta. Chat autentiche. Nomi modificati per proteggere i protagonisti.',
  'Avvertenza: ogni messaggio è reale. Nulla è stato inventato. I nomi sono stati cambiati.',
  'Le conversazioni mostrate sono successe davvero. I nomi sono stati alterati per ragioni di privacy.',
  'Attenzione: questa è una storia vera. Le chat non sono state ritoccate. Solo i nomi sono diversi.',
  'I messaggi di questo video sono autentici. I fatti sono reali. I nomi sono stati cambiati per riservatezza.',
  'Tutto quello che vedrai è realmente accaduto. Le conversazioni sono vere. I nomi sono di fantasia.',
  'Avviso: fatti reali e conversazioni reali. I nomi sono stati modificati per tutelare la privacy.',
  'Questa storia è autentica al 100%. Le chat sono originali. I nomi sono stati cambiati.',
  'Attenzione: ciò che leggerai non è inventato. È tutto vero. I nomi sono stati modificati per privacy.',
  'I dialoghi che stai per leggere sono reali. Per discrezione, i nomi sono stati cambiati.',
  'Tutto vero, niente di costruito. Le conversazioni sono autentiche. I nomi sono diversi per riservatezza.',
  'Avvertenza: questa vicenda è realmente accaduta. Le chat sono vere. I nomi sono stati cambiati.',
  'Le conversazioni che seguono sono reali. I fatti sono documentati. I nomi sono stati modificati per privacy.',
  'Quello che stai per leggere è successo davvero. Non c\'è alcuna finzione. Solo i nomi sono cambiati.',
  'Attenzione: storia vera, messaggi veri. I nomi sono stati sostituiti per proteggere le persone coinvolte.',
  'I fatti di questo reel sono autentici. Le chat non sono state alterate. I nomi sì, per riservatezza.',
  'Tutto ciò che vedrai è realmente accaduto. Le conversazioni sono fedeli. I nomi sono di fantasia.',
  'Questa è una vicenda reale. I messaggi sono quelli veri. I nomi sono stati cambiati per privacy.',
  'Avviso: le conversazioni sono autentiche e non modificate. I nomi sono stati alterati per riservatezza.',
  'Attenzione: nulla in questo video è inventato. È tutto vero. I nomi sono stati cambiati.',
  'I fatti che stai per scoprire sono reali. Le chat sono originali. Per privacy, i nomi sono diversi.',
  'Storia vera. Conversazioni autentiche. Nomi modificati per proteggere chi le ha vissute.',
  'Tutto quello che leggerai è accaduto realmente. Le chat sono vere. I nomi sono stati cambiati.',
  'Avvertenza: questi messaggi sono reali. Niente è stato romanzato. I nomi sono di fantasia.',
  'Le conversazioni mostrate sono autentiche. I fatti sono accaduti davvero. I nomi sono stati modificati per privacy.',
  'Attenzione: ciò che vedrai è tutto reale. Le chat non sono state ritoccate. I nomi sono stati cambiati.',
  'Questa storia è realmente accaduta. Le conversazioni sono vere. Per tutelare la privacy, i nomi sono stati cambiati.',
];

/**
 * Deterministically pick one disclaimer from the pool using a string seed (e.g.
 * the chat id). Same seed → same line; different seeds spread across the pool.
 */
export const pickDisclaimer = (seed: string): string => {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return INTRO_DISCLAIMERS[h % INTRO_DISCLAIMERS.length];
};
